name: "Encoding"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      args:
        default: "-p ."
        required: false
        type: string

jobs:
  encoding:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout target repo content"
        uses: actions/checkout@v3

      - name: "Checkout workflow repo content"
        uses: actions/checkout@v3
        with:
          repository: HaneulCheong/golden-oak-library
          path: workflow-repo

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ${GITHUB_WORKSPACE}/workflow-repo/.github/scripts/requirements.txt

      - name: "Run Python script"
        run: python ${GITHUB_WORKSPACE}/workflow-repo/.github/scripts/main.py ${{ inputs.args }}
